base_llm: gpt-4o-mini
domain: computer_vision
max_token_num: 1024
member_num: 3
related_paper_num: 10
result_path: Mixtral-8x7B
return_num: 1
reviewer_num: 1
stream: null
temperature: 0.0
top_p: null
experiment_model_name: gpt-4o-mini
write_proposal_strategy: default
max_env_run_num: 1